### ISSUE TITLE
Windows Defender detection

### ISSUE THREAD

**Issue by MrLGamer** [elbadcode/OpenGenshin#2]
When downloading the exe Windows defender is blocking it for the following reason:
Trojan:Win32/Wacatac.B!ml

![Screenshot 2024-02-10 153619](https://github.com/elbadcode/OpenGenshin/assets/54450456/a4cb09b1-8e6f-4781-81cf-84de75fc3abf)

VirusTotal scan:
https://www.virustotal.com/gui/file/308b75bfc953adf3f047a217acec9da4837f93a853254bd99b6ec30a566a058a

**Comment by elbadcode** [comment]
Source for the installer can be seen on this repo and I will soon upload the resources to make that usable but the issue is probably just because of the fps_unlocker. That tool is widely known to be safe but constantly gets virus flags from overzealous sites, see this [link just to put things in perspective](https://github.com/34736384/genshin-fps-unlock/issues/292)

I will see if I can sign and fix my build of it, if not I can scrap my changes and have my installer auto download from the main repo, but that may ultimately be prone to the same problem. At some point the skeptical user may have to just take a chance or build from source themselves which will of course be possible once I'm fully organized 

If you're open to taking a chance you should be able to just exclude the process in windows defender. It's not a perfect fix but it's not anything outrageous. All the major tools for Skyrim require this, as an example. And mind you, windows defender is a program that is so overprotective you can generate a Trojan flag just by making a simple regedit file to disable any code windows component, even if you type it yourself
